// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2619.PlyBot2018.subsystems;

import org.usfirst.frc2619.PlyBot2018.Robot;
import org.usfirst.frc2619.PlyBot2018.RobotMap;
import org.usfirst.frc2619.PlyBot2018.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.GearTooth;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Elevator extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	private static int lastValue = 0;
	public static int pos;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final WPI_TalonSRX motor = RobotMap.elevatorMotor;
    private final GearTooth counter = RobotMap.elevatorCounter;
    private final WPI_TalonSRX followerMotor = RobotMap.elevatorFollowerMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    //final variables for tuning the elevator.
    private static final int NUMBER_OF_POSITIONS = 5;
    private static final double MOTOR_POW = 0.6;
    private static final double CURRENT_LIMIT = 6;
    
    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    private boolean isForward() {
    	return (motor.get()>0);
    }
    
    private void setPow(double pow) {
    	count();
    	currentLimiting();
    	motor.set(pow);
    }
    
    public void runMotorFwd() {
    	setPow(MOTOR_POW);
    }
    
    public void runMotorRev() {
    	setPow(-MOTOR_POW);
    }
    
    public void stop() {
    	setPow(0);
    }
    
    private void count() {
    	int diff = counter.get() - lastValue;
    	if (!isForward())
    		diff = -diff;
    	pos += diff;
    	SmartDashboard.putNumber("ElevatorPosition:", pos);
    	SmartDashboard.putNumber("DefaultCounter:", counter.get());
    	lastValue = counter.get();
    }
    
    public void powToTarget(int target) {
    	count();
    	if (pos >= target) {
    		setPow(-MOTOR_POW);
    	}
    	else {
    		setPow(MOTOR_POW);
    	}
    }
    
    public int getElevatorPos() {
    	return pos;
    }
    
    public void setElevatorPos(int p) {
    	pos = p;
    }
    
    public boolean isPastTarget(int target) {
    	count();
    	checkLimitSwitches();
    	if ((motor.get()==0)) {
    		return false;
    	}else if (isForward()) {
    		return (pos>=target);
    	}else {
    		return (pos<=target-1);
    	}
    }
    
    public void resetPosBottom() {
    	pos = 0;
    	counter.reset();
    	lastValue = 0;
    }
    
    public void resetPosTop() {
    	pos = NUMBER_OF_POSITIONS;
    	counter.reset();
    	lastValue = 0;
    }
    
    public void reset() {
    	counter.reset();
    	pos = 0;
    	lastValue = 0;
    	SmartDashboard.putNumber("ElevatorPosition:", pos);
    }
    
    public boolean checkLimitSwitches() {
    	if (motor.getSensorCollection().isFwdLimitSwitchClosed()) {
    		resetPosTop();
    		return true;
    	}else if (motor.getSensorCollection().isRevLimitSwitchClosed())  {
    		resetPosBottom();
    		return true;
    	}
    	return false;
    }
    
    public void currentLimiting() {
		motor.configContinuousCurrentLimit((int) CURRENT_LIMIT, RobotMap.TIMEOUT_MS);
		motor.enableCurrentLimit(true);
		followerMotor.configContinuousCurrentLimit((int) CURRENT_LIMIT, RobotMap.TIMEOUT_MS);
		followerMotor.enableCurrentLimit(true);
	}
}

