// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2619.PlyBot2018;
import edu.wpi.first.wpilibj.SPI.Port;
import com.kauailabs.navx.frc.AHRS;
import com.ctre.phoenix.motorcontrol.ControlMode;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDController;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.smartdashboard.*;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX driveTrainLeftFrontMotor;
    public static WPI_TalonSRX driveTrainLeftRearMotor;
    public static WPI_TalonSRX driveTrainRightFrontMotor;
    public static WPI_TalonSRX driveTrainRightRearMotor;
    public static AnalogGyro driveTraindoNotUse;
    public static Solenoid shiftersSolenoid;
    public static Solenoid clawSolenoid;
    public static Encoder elevatorQuadratureEncoder;
    public static WPI_TalonSRX elevatorMotor;
    public static Encoder collectorEncoder;
    public static WPI_TalonSRX collectorMotor;
    public static Encoder reverseCollectorEncoder;
    public static WPI_TalonSRX reverseCollectorMotor;
    public static WPI_TalonSRX testCollectormotor1;
    public static Encoder testCollectorencoder1;
    public static PIDController testCollectorCollector;
    public static WPI_TalonSRX testCollectormotor2;
    public static Encoder testCollectorEncoder2;
    public static PIDController testCollectorReverseCollector;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public static final int TIMEOUT_MS = 100;
	
    public static AHRS driveTrainAHRS = new AHRS(Port.kMXP);
    
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainLeftFrontMotor = new WPI_TalonSRX(11);
        
        
        driveTrainLeftRearMotor = new WPI_TalonSRX(10);
        
        
        driveTrainRightFrontMotor = new WPI_TalonSRX(2);
        
        
        driveTrainRightRearMotor = new WPI_TalonSRX(3);
        
        
        driveTraindoNotUse = new AnalogGyro(1);
        LiveWindow.addSensor("DriveTrain", "doNotUse", driveTraindoNotUse);
        driveTraindoNotUse.setSensitivity(0.007);
        shiftersSolenoid = new Solenoid(0, 0);
        LiveWindow.addActuator("Shifters", "Solenoid", shiftersSolenoid);
        
        clawSolenoid = new Solenoid(0, 2);
        LiveWindow.addActuator("Claw", "Solenoid", clawSolenoid);
        
        elevatorQuadratureEncoder = new Encoder(0, 1, false, EncodingType.k4X);
        LiveWindow.addSensor("Elevator", "QuadratureEncoder", elevatorQuadratureEncoder);
        elevatorQuadratureEncoder.setDistancePerPulse(1.0);
        elevatorQuadratureEncoder.setPIDSourceType(PIDSourceType.kDisplacement);
        elevatorMotor = new WPI_TalonSRX(5);
        
        
        collectorEncoder = new Encoder(7, 8, false, EncodingType.k1X);
        LiveWindow.addSensor("Collector", "Encoder", collectorEncoder);
        collectorEncoder.setDistancePerPulse(1.0);
        collectorEncoder.setPIDSourceType(PIDSourceType.kRate);
        collectorMotor = new WPI_TalonSRX(30);
        
        
        reverseCollectorEncoder = new Encoder(10, 11, false, EncodingType.k1X);
        LiveWindow.addSensor("ReverseCollector", "Encoder", reverseCollectorEncoder);
        reverseCollectorEncoder.setDistancePerPulse(1.0);
        reverseCollectorEncoder.setPIDSourceType(PIDSourceType.kRate);
        reverseCollectorMotor = new WPI_TalonSRX(31);
        
        
        testCollectormotor1 = new WPI_TalonSRX(6);
        
        
        testCollectorencoder1 = new Encoder(5, 6, false, EncodingType.k1X);
        LiveWindow.addSensor("TestCollector", "encoder1", testCollectorencoder1);
        testCollectorencoder1.setDistancePerPulse(1.0);
        testCollectorencoder1.setPIDSourceType(PIDSourceType.kRate);
        testCollectorCollector = new PIDController(0.001, 1.0E-5, 0.0, 0.0, testCollectorencoder1, testCollectormotor1, 0.02);
        LiveWindow.addActuator("TestCollector", "Collector", testCollectorCollector);
        testCollectorCollector.setContinuous(false);
        testCollectorCollector.setAbsoluteTolerance(10.0);

        testCollectorCollector.setOutputRange(-1.0, 1.0);
        SmartDashboard.putData("TestCollector Collector", testCollectorCollector);
        testCollectormotor2 = new WPI_TalonSRX(7);
        
        
        testCollectorEncoder2 = new Encoder(2, 3, true, EncodingType.k1X);
        LiveWindow.addSensor("TestCollector", "Encoder2", testCollectorEncoder2);
        testCollectorEncoder2.setDistancePerPulse(1.0);
        testCollectorEncoder2.setPIDSourceType(PIDSourceType.kRate);
        testCollectorReverseCollector = new PIDController(0.001, 1.0E-5, 0.0, 0.0, testCollectorEncoder2, testCollectormotor2, 0.02);
        LiveWindow.addActuator("TestCollector", "ReverseCollector", testCollectorReverseCollector);
        testCollectorReverseCollector.setContinuous(false);
        testCollectorReverseCollector.setAbsoluteTolerance(10.0);

        testCollectorReverseCollector.setOutputRange(-1.0, 1.0);
        SmartDashboard.putData("TestCollector ReverseCollector", testCollectorReverseCollector);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainLeftRearMotor.follow(driveTrainLeftFrontMotor);
        driveTrainRightRearMotor.follow(driveTrainRightFrontMotor);
        driveTrainRightFrontMotor.setInverted(true);
        driveTrainRightRearMotor.setInverted(true);
		driveTrainAHRS = new AHRS(Port.kMXP);
		
        reverseCollectorMotor.setInverted(true);
        reverseCollectorEncoder.setReverseDirection(true);
    }
}
